# Generated by Django 4.2.4 on 2023-10-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descricao', models.TextField(default=0, max_length=9999)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.categoria')),
            ],
        ),
    ]
